### ISSUE TITLE
Consider removing Redis from database_cleaning.rb

### ISSUE THREAD

**Issue by TThurston** [DEFRA/ruby-services-team#15]
Currently we flush Redis between each unit and integration test.  I think originally this was done because we wanted to make sure a test didn't pass because of left-over results from the previous test.

It may make sense to clean Mongo and ElasticSearch between tests, as we often create registrations with the same searchable values in the test suites.  But for Redis this shouldn't be necessary, and in fact seems potentially harmful.  Thoughts @lewispb, @Cruikshanks, @bensagar-ea?

**Comment by lewispb** [comment]
Yeah, once before the suite runs, if at all, should be fine. I think it's the elastic search bit which is the slowest though.

**Comment by Cruikshanks** [comment]
It was so long ago now that the reasons for doing some of this stuff is a distant memory. However I have a whisper of a memory of tests randomly (but infrequently) failing if we didn't do this. It may well have actually been due to the problem we've now resolved (the whole thing with deleting old keys when the memory limit is hit) so I would say we should at least try.

**Comment by ben-sagar** [comment]
I agree.  If tests _are_ passing because of left-over results from the previous tests then that's probably a fault with the tests that, at the very least, should be captured (documented/commented) in the tests and ideally should be resolved so that the actual behaviour of the application is being tested.

I tend to think that the tests should be self-contained enough not to interfere with each other, but that might be a big change (not qualified to comment).

So yes, in summary, it gets my vote!

**Comment by TThurston** [comment]
Hmm... removing it causes test failures because the UUID of the registration is no longer unique in all tests.  So we need to figure out why and fix the tests accordingly.  I'm going to propose we leave things as they are for now to get the release out.

**Comment by Cruikshanks** [comment]
It is our intention to migrate the remaining functionality in the frontend into our new apps.

Hence have moved this across in the spirit of having a single list of issues, but it is not our intention to fix it because of this.

**Comment by irisfaraway** [comment]
Closing as we've agreed we won't fix this.
